feat(kbd_timeout): add privileges for kbd_timeout file
qu1x/huawei-wmi pull request #15
Opened 2022-06-20 20:25 UTC by tsivinsky

This pr adds kbd_timeout file to huawei-wmi group and copies file from /etc/default/huawei-wmi as default value.

2022-06-20 20:26 UTC, tsivinsky commented
sorry, if i did something wrong. it's my first PR. don't judge too harshly :)

2022-06-30 09:26 UTC, tsivinsky commented
i don't really know tbh, but i think, that it's available only on `feat/kbdlight` branch on Huawei-WMI repo, so I need to conditionally add it to group

2022-10-24 02:37 UTC, egormanga requested changes
LGTM otherwise.

2022-10-24 02:37 UTC, egormanga commented on generic/huawei-wmi-1.1.2/available
> +readonly KBD=kbdlight_timeout
I'd actually name it `$KLT` as there will be more `kbdlight_*` files.

2022-10-24 02:37 UTC, egormanga commented on generic/huawei-wmi-1.1.2/privilege
> +chmod g=u -- "$WMI$cct" "$WMI$FLS" "$WMI$KBD"
You can't just do this, as the file might not exist (e.g. an older version of the module is running, or the feature is not available in hardware). Add `[ -e "$WMI$KBD" ] &&`.

2023-02-21 15:11 UTC, n3vu0r commented on generic/huawei-wmi-1.1.2/available
> +readonly KBD=kbdlight_timeout
Makes sense, done.

2023-02-21 15:12 UTC, n3vu0r commented on generic/huawei-wmi-1.1.2/privilege
> +chmod g=u -- "$WMI$cct" "$WMI$FLS" "$WMI$KBD"
Done, also with `$WMI$PUL`. Thanks.

2023-02-21 15:15 UTC, n3vu0r commented
Thanks @egormanga for the review. I've merged latest changes into this PR branch and added your suggestions. I didn't test anything and I don't know how these new features work. Can you tell if it makes sense? Do you have a newer device to test this PR?

2023-02-22 12:11 UTC, n3vu0r commented
It basically comes down to whether following is true for all devices.

What the controller remembers and hence no default is required:

  * `fn_lock_state`

What the controller forgets and hence needs to be reinstated from defaults:

  * `charge_control_thresholds`
  * `kbdlight_timeout` (not available on all devices)
  * `power_unlock` (not available on all devices)
  * `smart_charge` (not available on all devices, is this a thing?)

All except for the last point is implemented in this branch but not tested.

2023-02-25 11:02 UTC, merged